name: That Geek Show
favicon: null
layout_spectrum: 0.76476
typography_spectrum: 0.74952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9aa19'
    - '#28becf'
    - '#fffaf3'
    - '#000000'
    - '#1c838f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
